# Generated by Django 3.1.7 on 2021-03-26 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_forma_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_habilidade',
            },
        ),
        migrations.CreateModel(
            name='TipoPrestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_tipo_prestador',
            },
        ),
        migrations.CreateModel(
            name='StatusServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_status_servico',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=25, unique=True)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('telefone', models.CharField(max_length=20)),
                ('dias_trabalho', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Domingo'), (2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira'), (7, 'Sábado')], max_length=13)),
                ('horario_trabalho', multiselectfield.db.fields.MultiSelectField(choices=[(1, '00:00'), (2, '01:00'), (3, '02:00'), (4, '03:00'), (5, '04:00'), (6, '05:00'), (7, '06:00'), (8, '07:00'), (9, '08:00'), (10, '09:00'), (11, '10:00'), (12, '11:00'), (13, '12:00'), (14, '13:00'), (15, '14:00'), (16, '15:00'), (17, '16:00'), (18, '17:00'), (19, '18:00'), (20, '19:00'), (21, '20:00'), (22, '21:00'), (23, '22:00'), (24, '23:00'), (25, '24:00')], max_length=65)),
                ('email', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('aceita_plataforma', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.formapagamento')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.habilidade')),
                ('tipo_costureiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.tipoprestador')),
            ],
            options={
                'db_table': 'tb_prestador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('aceita_plataforma', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('estrelas', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.prestador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.prestador')),
                ('status_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costureiro.statusservico')),
            ],
            options={
                'db_table': 'tb_agenda_servico',
            },
        ),
    ]
