# Generated by Django 3.1.7 on 2021-03-27 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costureiro', '0002_auto_20210327_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoprestador',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
